test: add gofmt & govet to test script

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,6 +1,57 @@
-#!/bin/sh -e
+#!/bin/bash -e
+#
+# Run all tests (not including functional)
+#   ./test
+#   ./test -v
+#
+# Run tests for one package
+#   PKG=./unit ./test
+#   PKG=ssh ./test
+#
 
-source build
+# Invoke ./cover for HTML output
+COVER=${COVER:-"-cover"}
 
-go test -i github.com/coreos-inc/auth/jose github.com/coreos-inc/auth/jose/sig
-go test -v github.com/coreos-inc/auth/jose github.com/coreos-inc/auth/jose/sig
+source ./build
+
+TESTABLE="jose jose/sig"
+FORMATTABLE="$TESTABLE examples/app oauth2 oidc pkg/http provider"
+
+# user has not provided PKG override
+if [ -z "$PKG" ]; then
+	TEST=$TESTABLE
+	FMT=$FORMATTABLE
+
+# user has provided PKG override
+else
+	# strip out slashes and dots from PKG=./foo/
+	TEST=${PKG//\//}
+	TEST=${TEST//./}
+
+	# only run gofmt on packages provided by user
+	FMT="$TEST"
+fi
+
+# split TEST into an array and prepend repo path to each local package
+split=(${TEST// / })
+TEST=${split[@]/#/github.com/coreos-inc/auth/}
+
+echo "Running tests..."
+go test -i ${TEST}
+go test ${COVER} $@ ${TEST}
+
+echo "Checking gofmt..."
+fmtRes=$(gofmt -l $FMT)
+if [ -n "${fmtRes}" ]; then
+	echo -e "gofmt checking failed:\n${fmtRes}"
+	exit 255
+fi
+
+echo "Checking govet..."
+vetRes=$(go vet $TEST)
+if [ -n "${vetRes}" ]; then
+	echo -e "govet checking failed:\n${vetRes}"
+	exit 255
+fi
+
+echo "Success"
